# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FinalCountdown < Formula
  desc ""
  homepage "https://github.com/wecraftforfun/homebrew-tools"
  version "0.9.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wecraftforfun/final-countdown/releases/download/v0.9.6/final-countdown_0.9.6_Darwin_arm64.tar.gz"
      sha256 "d4931794bbdffd3b4db5c98b32ae0440cfdec70c92f7f4fe826a7d8339113f5b"

      def install
        bin.install "final-countdown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wecraftforfun/final-countdown/releases/download/v0.9.6/final-countdown_0.9.6_Darwin_x86_64.tar.gz"
      sha256 "32ebfd8789bf0304bfc0c674c964b89845e902d4150692e33e98b42414536174"

      def install
        bin.install "final-countdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wecraftforfun/final-countdown/releases/download/v0.9.6/final-countdown_0.9.6_Linux_x86_64.tar.gz"
      sha256 "940ef89ede8b68379eb64dc13b13618f590816a8b77608e7afdb2cb595c54e66"

      def install
        bin.install "final-countdown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wecraftforfun/final-countdown/releases/download/v0.9.6/final-countdown_0.9.6_Linux_arm64.tar.gz"
      sha256 "519d239ace4e40b712ee52e3950ffd72df06737bcfa0073c2b9686ce5b2478cd"

      def install
        bin.install "final-countdown"
      end
    end
  end
end
