# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LaunchTui < Formula
  desc ""
  homepage "https://github.com/wecraftforfun/homebrew-tools"
  version "1.0.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wecraftforfun/launch-tui/releases/download/v1.0.0/launch-tui_1.0.0_Darwin_arm64.tar.gz"
      sha256 "3c4d0da78d6f62c318b626614354f1832761de07c0cce15d9eaec7f2eb302b2e"

      def install
        bin.install "launch-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wecraftforfun/launch-tui/releases/download/v1.0.0/launch-tui_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "c036c4af6ed496ff9e40edef42f1b1ec7f443e7c6e7379b70a708f979ee87751"

      def install
        bin.install "launch-tui"
      end
    end
  end
end
